eureka:
  instance:
    hostname: Contact
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

server:
  port: 8084
spring:
  application:
    name: Contact
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/gestion_labo
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

application:
  config:
    contacts-url: http://localhost:8222/api/contacts

management:
  tracing:
    sampling:
      probability: 1.0